#!/bin/bash
# Build Native deployment from common files
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

TARGET_DIR="../orangescrum-cloud-native"
VERSION="${VERSION:-v26.1.1}"

echo "=========================================="
echo "OrangeScrum Native Deployment Builder"
echo "=========================================="
echo "Target: $TARGET_DIR"
echo "Version: $VERSION"
echo ""

# Create target directory
mkdir -p "$TARGET_DIR"

# Check if binary exists
BINARY="./orangescrum-app/osv4-prod"
if [ ! -f "$BINARY" ]; then
    echo "[WARNING]  Warning: Binary not found: $BINARY"
    echo "   Run: python ../build.py to build the binary first"
    echo ""
fi

# Copy Native-specific files
echo "Copying Native-specific files..."

echo "  [OK] run-native.sh"
cp run-native.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/run-native.sh"

echo "  [OK] run.sh"
cp run.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/run.sh"

echo "  [OK] package.sh"
cp package.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/package.sh"

if [ -f "caddy.sh" ]; then
    echo "  [OK] caddy.sh"
    cp caddy.sh "$TARGET_DIR/"
    chmod +x "$TARGET_DIR/caddy.sh"
fi

# Copy environment files for Native
echo "  [OK] .env.example"
cp .env.example "$TARGET_DIR/"

if [ -f ".env.full.example" ]; then
    echo "  [OK] .env.full.example"
    cp .env.full.example "$TARGET_DIR/"
fi

# Copy common files
echo ""
echo "Copying common files..."

echo "  [OK] config/"
cp -r config "$TARGET_DIR/"

echo "  [OK] docs/"
cp -r docs "$TARGET_DIR/"

echo "  [OK] Helper scripts"
cp cake.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/cake.sh"

cp queue-worker.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/queue-worker.sh"

cp validate-env.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/validate-env.sh"

echo "  [OK] Configuration documentation"
cp CONFIGS.md "$TARGET_DIR/"

# Copy binary if it exists
if [ -f "$BINARY" ]; then
    echo ""
    echo "Copying FrankenPHP binary..."
    mkdir -p "$TARGET_DIR/orangescrum-app"
    cp "$BINARY" "$TARGET_DIR/orangescrum-app/"
    chmod +x "$TARGET_DIR/orangescrum-app/osv4-prod"
    SIZE=$(du -h "$TARGET_DIR/orangescrum-app/osv4-prod" | cut -f1)
    echo "  [OK] Binary copied ($SIZE)"
else
    mkdir -p "$TARGET_DIR/orangescrum-app"
    echo "  [WARNING]  Binary not copied (will be created during build)"
fi

# Create README for Native deployment
echo ""
echo "Creating Native-specific README..."
cat > "$TARGET_DIR/README.md" << 'NATIVEREADME'
# OrangeScrum FrankenPHP - Native Deployment

This directory contains the native (non-Docker) deployment configuration for OrangeScrum as a FrankenPHP static binary.

> **Note:** This folder is auto-generated by `build-native.sh` from the common files in `orangescrum-cloud/`.

## Native Native Deployment Overview

This setup runs OrangeScrum directly on your host system using the FrankenPHP static binary:
- **FrankenPHP static binary** with embedded PHP 8.3, Caddy server, and application code
- **Direct system execution** for maximum performance
- **Automated migrations** and database setup
- **Systemd integration** for production deployments
- **No container overhead** - runs natively on Linux, macOS, Windows

## [WARNING] Production Deployment

**Before deploying to production**, please read:

[DOCS] **[Production Readiness Summary](docs/PRODUCTION_READINESS_SUMMARY.md)** - Start here!
[DOCS] **[Native Production Guide](docs/PRODUCTION_DEPLOYMENT_NATIVE.md)** - Comprehensive deployment guide

---

## Quick Start (Development)

### Prerequisites

- **FrankenPHP binary** in `orangescrum-app/osv4-prod` (build with cloud-builder)
- **PostgreSQL client** (`psql`) installed
- **PostgreSQL**, **Redis**, and **S3-compatible storage** services running

### 1. Build the Binary

From the parent directory:

```bash
cd /home/ubuntu/workspace/os-next/cloud-builder
python build.py
# This automatically builds this Native deployment folder
```

### 2. Setup Environment

```bash
# Copy environment template
cp .env.example .env

# Edit configuration (required - set database, security settings)
nano .env
```

### 3. Validate Configuration

```bash
# Check environment setup
./validate-env.sh
```

### 4. Run Application

```bash
# Development mode (foreground, logs in terminal)
./run-native.sh

# Production mode (background daemon)
DAEMON=true ./run-native.sh &
```

**Access:** http://localhost:8080

---

## Rebuilding This Folder

If common files are updated, rebuild this folder:

```bash
cd ../orangescrum-cloud
./build-native.sh
```

---

## Configuration

See [CONFIGS.md](CONFIGS.md) for full configuration options.

Generate secure values:
```bash
# Security salt
openssl rand -base64 32

# Database password
openssl rand -base64 24
```

---

## Production Deployment

### Systemd Service (Linux)

Create `/etc/systemd/system/orangescrum.service`:

```ini
[Unit]
Description=OrangeScrum FrankenPHP Application
After=network.target postgresql.service redis.service

[Service]
Type=simple
User=orangescrum
Group=orangescrum
WorkingDirectory=/opt/orangescrum
EnvironmentFile=/opt/orangescrum/.env
ExecStart=/opt/orangescrum/orangescrum-app/osv4-prod php-server --listen :8080
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Enable and start:

```bash
sudo systemctl enable orangescrum
sudo systemctl start orangescrum
sudo systemctl status orangescrum
```

See [docs/PRODUCTION_DEPLOYMENT_NATIVE.md](docs/PRODUCTION_DEPLOYMENT_NATIVE.md) for complete production setup.

---

## Packaging for Deployment

Create a deployment package:

```bash
./package.sh
# Creates: orangescrum-frankenphp-v26.1.1.tar.gz
```

---

## Documentation

- [CONFIGS.md](CONFIGS.md) - Configuration reference
- [docs/PRODUCTION_DEPLOYMENT_NATIVE.md](docs/PRODUCTION_DEPLOYMENT_NATIVE.md) - Production guide
- [docs/DEPLOYMENT.md](docs/DEPLOYMENT.md) - General deployment guide

---

## Source Files

This deployment folder is built from:
- **Common files:** `../orangescrum-cloud/` (config, docs, scripts)
- **Native-specific:** `../orangescrum-cloud/` (run-native.sh, run.sh, package.sh, caddy.sh)
- **Build script:** `../orangescrum-cloud/build-native.sh`

---

## License

See parent directory for license information.
NATIVEREADME

echo "  [OK] README.md created"

echo ""
echo "=========================================="
echo "[OK] Native deployment built successfully!"
echo "=========================================="
echo ""
echo "Target directory: $TARGET_DIR"
echo ""
echo "Next steps:"
echo "  cd $TARGET_DIR"
echo "  cp .env.example .env"
echo "  nano .env  # Configure your settings"
echo "  ./validate-env.sh"
echo "  ./run-native.sh"
echo ""
