#!/bin/bash
# Build Docker deployment from common files
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

TARGET_DIR="../orangescrum-cloud-docker"
VERSION="${VERSION:-v26.1.1}"

echo "=========================================="
echo "OrangeScrum Docker Deployment Builder"
echo "=========================================="
echo "Target: $TARGET_DIR"
echo "Version: $VERSION"
echo ""

# Create target directory
mkdir -p "$TARGET_DIR"

# Check if binary exists
BINARY="./orangescrum-app/osv4-prod"
if [ ! -f "$BINARY" ]; then
    echo "[WARNING]  Warning: Binary not found: $BINARY"
    echo "   Run: python ../build.py to build the binary first"
    echo ""
fi

# Copy Docker-specific files
echo "Copying Docker-specific files..."
echo "  [OK] Dockerfile"
cp Dockerfile "$TARGET_DIR/"

echo "  [OK] docker-compose.yaml"
cp docker-compose.yaml "$TARGET_DIR/"

echo "  [OK] docker-compose.services.yml"
cp docker-compose.services.yml "$TARGET_DIR/"

echo "  [OK] entrypoint.sh"
cp entrypoint.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/entrypoint.sh"

if [ -f ".dockerignore" ]; then
    echo "  [OK] .dockerignore"
    cp .dockerignore "$TARGET_DIR/"
fi

# Copy environment file for Docker
echo "  [OK] .env (from .env.docker)"
if [ -f ".env.docker" ]; then
    cp .env.docker "$TARGET_DIR/.env"
    cp .env.docker "$TARGET_DIR/.env.example"
else
    cp .env.example "$TARGET_DIR/.env.example"
fi

# Copy common files
echo ""
echo "Copying common files..."

echo "  [OK] config/"
cp -r config "$TARGET_DIR/"

echo "  [OK] docs/"
cp -r docs "$TARGET_DIR/"

echo "  [OK] Helper scripts"
cp cake.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/cake.sh"

cp queue-worker.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/queue-worker.sh"

cp validate-env.sh "$TARGET_DIR/"
chmod +x "$TARGET_DIR/validate-env.sh"

echo "  [OK] Configuration documentation"
cp CONFIGS.md "$TARGET_DIR/"

# Copy binary if it exists
if [ -f "$BINARY" ]; then
    echo ""
    echo "Copying FrankenPHP binary..."
    mkdir -p "$TARGET_DIR/orangescrum-app"
    cp "$BINARY" "$TARGET_DIR/orangescrum-app/"
    chmod +x "$TARGET_DIR/orangescrum-app/osv4-prod"
    SIZE=$(du -h "$TARGET_DIR/orangescrum-app/osv4-prod" | cut -f1)
    echo "  [OK] Binary copied ($SIZE)"
else
    mkdir -p "$TARGET_DIR/orangescrum-app"
    echo "  [WARNING]  Binary not copied (will be created during build)"
fi

# Create README for Docker deployment
echo ""
echo "Creating Docker-specific README..."
cat > "$TARGET_DIR/README.md" << 'DOCKERREADME'
# OrangeScrum FrankenPHP - Docker Deployment

This directory contains the Docker deployment configuration for OrangeScrum as a FrankenPHP static binary.

> **Note:** This folder is auto-generated by `build-docker.sh` from the common files in `orangescrum-cloud/`.

## Docker Docker Deployment Overview

This setup uses Docker containers to run OrangeScrum with FrankenPHP. It includes:
- **FrankenPHP static binary** with embedded PHP 8.3, Caddy server, and application code
- **Docker Compose** orchestration for easy multi-container management
- **Automated migrations** and database setup
- **Health checks** and monitoring
- **Queue workers** for background job processing

## [WARNING] Production Deployment

**Before deploying to production**, please read:

[DOCS] **[Production Readiness Summary](docs/PRODUCTION_READINESS_SUMMARY.md)** - Start here!
[DOCS] **[Docker Production Guide](docs/PRODUCTION_DEPLOYMENT_DOCKER.md)** - Comprehensive deployment guide

---

## Quick Start (Development)

### Prerequisites

- Docker and Docker Compose installed
- PostgreSQL client (`psql`) for database operations
- FrankenPHP binary in `orangescrum-app/osv4-prod` (build with cloud-builder)

### 1. Build the Binary

From the parent directory:

```bash
cd /home/ubuntu/workspace/os-next/cloud-builder
python build.py
# This automatically builds this Docker deployment folder
```

### 2. Setup Environment

```bash
# Edit configuration (required - set database, security settings)
nano .env
```

### 3. Start Infrastructure Services

```bash
# Start database, cache, storage, mail
docker-compose -f docker-compose.services.yml up -d

# Verify services running
docker-compose -f docker-compose.services.yml ps
```

### 4. Run Application

```bash
# Build and start the application
docker-compose up -d

# View logs
docker-compose logs -f orangescrum-app

# Check health
docker-compose ps
```

**Access:** http://localhost:8080

---

## Rebuilding This Folder

If common files are updated, rebuild this folder:

```bash
cd ../orangescrum-cloud
./build-docker.sh
```

---

## Configuration

See [CONFIGS.md](CONFIGS.md) for full configuration options.

Key environment variables in `.env`:

```bash
# Database (PostgreSQL)
DB_HOST=192.168.49.10
DB_USERNAME=postgres
DB_PASSWORD=your-secure-password-here
DB_NAME=orangescrum

# Security
SECURITY_SALT=__CHANGE_THIS_TO_RANDOM_STRING__

# Application
FULL_BASE_URL=http://localhost:8080
APP_PORT=8080
```

---

## Documentation

- [CONFIGS.md](CONFIGS.md) - Configuration reference
- [docs/PRODUCTION_DEPLOYMENT_DOCKER.md](docs/PRODUCTION_DEPLOYMENT_DOCKER.md) - Production guide
- [docs/DEPLOYMENT.md](docs/DEPLOYMENT.md) - General deployment guide

---

## Source Files

This deployment folder is built from:
- **Common files:** `../orangescrum-cloud/` (config, docs, scripts)
- **Docker-specific:** `../orangescrum-cloud/` (Dockerfile, docker-compose.yaml, entrypoint.sh)
- **Build script:** `../orangescrum-cloud/build-docker.sh`

---

## License

See parent directory for license information.
DOCKERREADME

echo "  [OK] README.md created"

echo ""
echo "=========================================="
echo "[OK] Docker deployment built successfully!"
echo "=========================================="
echo ""
echo "Target directory: $TARGET_DIR"
echo ""
echo "Next steps:"
echo "  cd $TARGET_DIR"
echo "  nano .env  # Configure your settings"
echo "  docker-compose -f docker-compose.services.yml up -d  # Start infrastructure"
echo "  docker-compose up -d  # Start application"
echo ""
